//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.Geho.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.Geho.Gui.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher.
        /// </summary>
        public static string Btn_Display {
            get {
                return ResourceManager.GetString("Btn_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des groupes.
        /// </summary>
        public static string Btn_GroupMgmt {
            get {
                return ResourceManager.GetString("Btn_GroupMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion du personnel.
        /// </summary>
        public static string Btn_HrMgmt {
            get {
                return ResourceManager.GetString("Btn_HrMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les temps de midi.
        /// </summary>
        public static string Btn_ManageLunch {
            get {
                return ResourceManager.GetString("Btn_ManageLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string Btn_Print {
            get {
                return ResourceManager.GetString("Btn_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauver.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les horaires.
        /// </summary>
        public static string Btn_ScheduleDisplay {
            get {
                return ResourceManager.GetString("Btn_ScheduleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des horaires.
        /// </summary>
        public static string Btn_ScheduleManagement {
            get {
                return ResourceManager.GetString("Btn_ScheduleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        public static string Btn_Update {
            get {
                return ResourceManager.GetString("Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;absence est invalide. 
        ///Vérifiez:
        ///- qu&apos;aucune absence existe pour cette personne à cette période
        ///- que l&apos;absence est dans le futur.
        /// </summary>
        public static string BusinessRule_InvalidAbsence {
            get {
                return ResourceManager.GetString("BusinessRule_InvalidAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclure les semaines passées.
        /// </summary>
        public static string Cb_ExcludePastWeek {
            get {
                return ResourceManager.GetString("Cb_ExcludePastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educateur?.
        /// </summary>
        public static string Cb_IsEducator {
            get {
                return ResourceManager.GetString("Cb_IsEducator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagiaire?.
        /// </summary>
        public static string Cb_IsTrainee {
            get {
                return ResourceManager.GetString("Cb_IsTrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to après-midi.
        /// </summary>
        public static string Day_Afternoon {
            get {
                return ResourceManager.GetString("Day_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to journée.
        /// </summary>
        public static string Day_AllDay {
            get {
                return ResourceManager.GetString("Day_AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendredi.
        /// </summary>
        public static string Day_Friday {
            get {
                return ResourceManager.GetString("Day_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lundi.
        /// </summary>
        public static string Day_Monday {
            get {
                return ResourceManager.GetString("Day_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matin.
        /// </summary>
        public static string Day_Morning {
            get {
                return ResourceManager.GetString("Day_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samedi.
        /// </summary>
        public static string Day_Saturday {
            get {
                return ResourceManager.GetString("Day_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimanche.
        /// </summary>
        public static string Day_Sunday {
            get {
                return ResourceManager.GetString("Day_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeudi.
        /// </summary>
        public static string Day_Thursday {
            get {
                return ResourceManager.GetString("Day_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mardi.
        /// </summary>
        public static string Day_Tuesday {
            get {
                return ResourceManager.GetString("Day_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercredi.
        /// </summary>
        public static string Day_Wednesday {
            get {
                return ResourceManager.GetString("Day_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absences.
        /// </summary>
        public static string Header_Absences {
            get {
                return ResourceManager.GetString("Header_Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activités.
        /// </summary>
        public static string Header_Activities {
            get {
                return ResourceManager.GetString("Header_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité.
        /// </summary>
        public static string Header_Activity {
            get {
                return ResourceManager.GetString("Header_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer activité.
        /// </summary>
        public static string Header_AddActivity {
            get {
                return ResourceManager.GetString("Header_AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer groupe.
        /// </summary>
        public static string Header_AddGroup {
            get {
                return ResourceManager.GetString("Header_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter du personnel.
        /// </summary>
        public static string Header_AddPerson {
            get {
                return ResourceManager.GetString("Header_AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une semaine.
        /// </summary>
        public static string Header_AddWeek {
            get {
                return ResourceManager.GetString("Header_AddWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activités administratives.
        /// </summary>
        public static string Header_AdministrativeTasks {
            get {
                return ResourceManager.GetString("Header_AdministrativeTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bénéficiaires.
        /// </summary>
        public static string Header_Beneficiary {
            get {
                return ResourceManager.GetString("Header_Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour.
        /// </summary>
        public static string Header_Day {
            get {
                return ResourceManager.GetString("Header_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jours.
        /// </summary>
        public static string Header_Days {
            get {
                return ResourceManager.GetString("Header_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les horaires.
        /// </summary>
        public static string Header_DisplaySchedule {
            get {
                return ResourceManager.GetString("Header_DisplaySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string Header_Edition {
            get {
                return ResourceManager.GetString("Header_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educateurs.
        /// </summary>
        public static string Header_Educators {
            get {
                return ResourceManager.GetString("Header_Educators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Header_ErrorMsg {
            get {
                return ResourceManager.GetString("Header_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupes.
        /// </summary>
        public static string Header_Groups {
            get {
                return ResourceManager.GetString("Header_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps de midi.
        /// </summary>
        public static string Header_LunchTime {
            get {
                return ResourceManager.GetString("Header_LunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les absences.
        /// </summary>
        public static string Header_ManageAbsence {
            get {
                return ResourceManager.GetString("Header_ManageAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les activités.
        /// </summary>
        public static string Header_ManageAtivity {
            get {
                return ResourceManager.GetString("Header_ManageAtivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les groupes.
        /// </summary>
        public static string Header_ManageGroup {
            get {
                return ResourceManager.GetString("Header_ManageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer visites médicales.
        /// </summary>
        public static string Header_ManageMedicalExams {
            get {
                return ResourceManager.GetString("Header_ManageMedicalExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des horaires.
        /// </summary>
        public static string Header_ManageSchedule {
            get {
                return ResourceManager.GetString("Header_ManageSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visites médicales.
        /// </summary>
        public static string Header_MedicalExam {
            get {
                return ResourceManager.GetString("Header_MedicalExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment.
        /// </summary>
        public static string Header_Moment {
            get {
                return ResourceManager.GetString("Header_Moment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bénéficiaires présents.
        /// </summary>
        public static string Header_PresentBeneficiary {
            get {
                return ResourceManager.GetString("Header_PresentBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impression.
        /// </summary>
        public static string Header_Print {
            get {
                return ResourceManager.GetString("Header_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage de l&apos;erreur.
        /// </summary>
        public static string Header_ShowError {
            get {
                return ResourceManager.GetString("Header_ShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace.
        /// </summary>
        public static string Header_StackTrace {
            get {
                return ResourceManager.GetString("Header_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horaires.
        /// </summary>
        public static string Header_TimeTable {
            get {
                return ResourceManager.GetString("Header_TimeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupations.
        /// </summary>
        public static string Header_WorkSummary {
            get {
                return ResourceManager.GetString("Header_WorkSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personne absente:.
        /// </summary>
        public static string Lbl_AbsentPerson {
            get {
                return ResourceManager.GetString("Lbl_AbsentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité:.
        /// </summary>
        public static string Lbl_Activity {
            get {
                return ResourceManager.GetString("Lbl_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Après-midi.
        /// </summary>
        public static string Lbl_Afternoon {
            get {
                return ResourceManager.GetString("Lbl_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à.
        /// </summary>
        public static string Lbl_At {
            get {
                return ResourceManager.GetString("Lbl_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bénéficiaires:.
        /// </summary>
        public static string Lbl_Beneficiaries {
            get {
                return ResourceManager.GetString("Lbl_Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bénéficiaires: .
        /// </summary>
        public static string Lbl_BeneficiariesCount {
            get {
                return ResourceManager.GetString("Lbl_BeneficiariesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour:.
        /// </summary>
        public static string Lbl_Day {
            get {
                return ResourceManager.GetString("Lbl_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educateurs:.
        /// </summary>
        public static string Lbl_Educators {
            get {
                return ResourceManager.GetString("Lbl_Educators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre d&apos;éducateurs par groupe:.
        /// </summary>
        public static string Lbl_EducatorsToShow {
            get {
                return ResourceManager.GetString("Lbl_EducatorsToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        public static string Lbl_From {
            get {
                return ResourceManager.GetString("Lbl_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe:.
        /// </summary>
        public static string Lbl_Group {
            get {
                return ResourceManager.GetString("Lbl_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM.
        /// </summary>
        public static string Lbl_MedicalExam {
            get {
                return ResourceManager.GetString("Lbl_MedicalExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matin.
        /// </summary>
        public static string Lbl_Morning {
            get {
                return ResourceManager.GetString("Lbl_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom:.
        /// </summary>
        public static string Lbl_Name {
            get {
                return ResourceManager.GetString("Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordre:.
        /// </summary>
        public static string Lbl_Order {
            get {
                return ResourceManager.GetString("Lbl_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaine à afficher:.
        /// </summary>
        public static string Lbl_SelectDate {
            get {
                return ResourceManager.GetString("Lbl_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment:.
        /// </summary>
        public static string Lbl_Span {
            get {
                return ResourceManager.GetString("Lbl_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Lbl_Status {
            get {
                return ResourceManager.GetString("Lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom:.
        /// </summary>
        public static string Lbl_Surname {
            get {
                return ResourceManager.GetString("Lbl_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to au.
        /// </summary>
        public static string Lbl_To {
            get {
                return ResourceManager.GetString("Lbl_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au.
        /// </summary>
        public static string Lbl_ToU {
            get {
                return ResourceManager.GetString("Lbl_ToU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaine du.
        /// </summary>
        public static string Lbl_WeekOf {
            get {
                return ResourceManager.GetString("Lbl_WeekOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaine à ajouter:.
        /// </summary>
        public static string Lbl_WeekToAdd {
            get {
                return ResourceManager.GetString("Lbl_WeekToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des horaires.
        /// </summary>
        public static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence créée..
        /// </summary>
        public static string Msg_AbsenceCreated {
            get {
                return ResourceManager.GetString("Msg_AbsenceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence/ visite médicale supprimée..
        /// </summary>
        public static string Msg_AbsenceDeleted {
            get {
                return ResourceManager.GetString("Msg_AbsenceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité &apos;{0}&apos; créée..
        /// </summary>
        public static string Msg_ActivityCreated {
            get {
                return ResourceManager.GetString("Msg_ActivityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité &apos;{0}&apos; supprimé..
        /// </summary>
        public static string Msg_ActivityDeleted {
            get {
                return ResourceManager.GetString("Msg_ActivityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} a été ajouté au groupe.
        /// </summary>
        public static string Msg_AddPersonInGroup {
            get {
                return ResourceManager.GetString("Msg_AddPersonInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette semaine n&apos;existe pas. Voulez-vous la créer?.
        /// </summary>
        public static string Msg_AskCreateNewWeek {
            get {
                return ResourceManager.GetString("Msg_AskCreateNewWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer cette absence?.
        /// </summary>
        public static string Msg_AskDeleteAbsence {
            get {
                return ResourceManager.GetString("Msg_AskDeleteAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer l&apos;activité &quot;{0}&quot;?.
        /// </summary>
        public static string Msg_AskDeleteActivity {
            get {
                return ResourceManager.GetString("Msg_AskDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer le groupe &quot;{0}&quot;?.
        /// </summary>
        public static string Msg_AskDeleteGroup {
            get {
                return ResourceManager.GetString("Msg_AskDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous effacer {0} {1}?.
        /// </summary>
        public static string Msg_AskDeletePerson {
            get {
                return ResourceManager.GetString("Msg_AskDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ces personnes ne peuvent être assignées puisque déjà occupées:.
        /// </summary>
        public static string Msg_Error_EducatorsAreBusy {
            get {
                return ResourceManager.GetString("Msg_Error_EducatorsAreBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe &apos;{0}&apos; créé..
        /// </summary>
        public static string Msg_GroupCreated {
            get {
                return ResourceManager.GetString("Msg_GroupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe &apos;{0}&apos; supprimé..
        /// </summary>
        public static string Msg_GroupDeleted {
            get {
                return ResourceManager.GetString("Msg_GroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement....
        /// </summary>
        public static string Msg_Loading {
            get {
                return ResourceManager.GetString("Msg_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps de midi mis à jour..
        /// </summary>
        public static string Msg_LunchesUpdated {
            get {
                return ResourceManager.GetString("Msg_LunchesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visite médicale créée..
        /// </summary>
        public static string Msg_MedicalExamAdded {
            get {
                return ResourceManager.GetString("Msg_MedicalExamAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune date sélectionnée.
        /// </summary>
        public static string Msg_NoDateSelected {
            get {
                return ResourceManager.GetString("Msg_NoDateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun groupe sélectionné.
        /// </summary>
        public static string Msg_NoGroupSelected {
            get {
                return ResourceManager.GetString("Msg_NoGroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt..
        /// </summary>
        public static string Msg_NoMessage {
            get {
                return ResourceManager.GetString("Msg_NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a pas de semaine à afficher..
        /// </summary>
        public static string Msg_NoWeekToDisplay {
            get {
                return ResourceManager.GetString("Msg_NoWeekToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordre:.
        /// </summary>
        public static string Msg_Order {
            get {
                return ResourceManager.GetString("Msg_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} a été créé..
        /// </summary>
        public static string Msg_PersonAdded {
            get {
                return ResourceManager.GetString("Msg_PersonAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} a été suprimé..
        /// </summary>
        public static string Msg_PersonDeleted {
            get {
                return ResourceManager.GetString("Msg_PersonDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impression des documents.
        /// </summary>
        public static string Msg_Print {
            get {
                return ResourceManager.GetString("Msg_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt..
        /// </summary>
        public static string Msg_Ready {
            get {
                return ResourceManager.GetString("Msg_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} a été supprimé du groupe.
        /// </summary>
        public static string Msg_RemovePersonFromGroup {
            get {
                return ResourceManager.GetString("Msg_RemovePersonFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horaire sauvegardé.
        /// </summary>
        public static string Msg_SavedSchedule {
            get {
                return ResourceManager.GetString("Msg_SavedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage du {0}.
        /// </summary>
        public static string Msg_ShowDayInWeek {
            get {
                return ResourceManager.GetString("Msg_ShowDayInWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&apos;est un stagiaire.
        /// </summary>
        public static string Msg_ThisIsATrainee {
            get {
                return ResourceManager.GetString("Msg_ThisIsATrainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour effectuée..
        /// </summary>
        public static string Msg_UpdateDone {
            get {
                return ResourceManager.GetString("Msg_UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaine du {0} ajoutée.
        /// </summary>
        public static string Msg_WeekAdded {
            get {
                return ResourceManager.GetString("Msg_WeekAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activé.
        /// </summary>
        public static string Status_IsActive {
            get {
                return ResourceManager.GetString("Status_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactivé.
        /// </summary>
        public static string Status_IsNotActive {
            get {
                return ResourceManager.GetString("Status_IsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendredi.
        /// </summary>
        public static string Tab_Friday {
            get {
                return ResourceManager.GetString("Tab_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lundi.
        /// </summary>
        public static string Tab_Monday {
            get {
                return ResourceManager.GetString("Tab_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeudi.
        /// </summary>
        public static string Tab_Thursday {
            get {
                return ResourceManager.GetString("Tab_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mardi.
        /// </summary>
        public static string Tab_Tuesday {
            get {
                return ResourceManager.GetString("Tab_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercredi.
        /// </summary>
        public static string Tab_Wednesday {
            get {
                return ResourceManager.GetString("Tab_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebdo.
        /// </summary>
        public static string Tab_Week {
            get {
                return ResourceManager.GetString("Tab_Week", resourceCulture);
            }
        }
    }
}
