//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Probel.Geho.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Probel.Geho.Gui.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des groupes.
        /// </summary>
        public static string Btn_GroupMgmt {
            get {
                return ResourceManager.GetString("Btn_GroupMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion du personnel.
        /// </summary>
        public static string Btn_HrMgmt {
            get {
                return ResourceManager.GetString("Btn_HrMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des horaires.
        /// </summary>
        public static string Btn_ScheduleManagement {
            get {
                return ResourceManager.GetString("Btn_ScheduleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        public static string Btn_Update {
            get {
                return ResourceManager.GetString("Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;absence est invalide. 
        ///Vérifiez:
        ///- qu&apos;aucune absence existe pour cette personne à cette période
        ///- que l&apos;absence est dans le futur.
        /// </summary>
        public static string BusinessRule_InvalidAbsence {
            get {
                return ResourceManager.GetString("BusinessRule_InvalidAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educateur?.
        /// </summary>
        public static string Cb_IsEducator {
            get {
                return ResourceManager.GetString("Cb_IsEducator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to après-midi.
        /// </summary>
        public static string Day_Afternoon {
            get {
                return ResourceManager.GetString("Day_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendredi.
        /// </summary>
        public static string Day_Friday {
            get {
                return ResourceManager.GetString("Day_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lundi.
        /// </summary>
        public static string Day_Monday {
            get {
                return ResourceManager.GetString("Day_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matin.
        /// </summary>
        public static string Day_Morning {
            get {
                return ResourceManager.GetString("Day_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samedi.
        /// </summary>
        public static string Day_Saturday {
            get {
                return ResourceManager.GetString("Day_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimanche.
        /// </summary>
        public static string Day_Sunday {
            get {
                return ResourceManager.GetString("Day_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeudi.
        /// </summary>
        public static string Day_Thursday {
            get {
                return ResourceManager.GetString("Day_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mardi.
        /// </summary>
        public static string Day_Tuesday {
            get {
                return ResourceManager.GetString("Day_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercredi.
        /// </summary>
        public static string Day_Wednesday {
            get {
                return ResourceManager.GetString("Day_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absences.
        /// </summary>
        public static string Header_Absences {
            get {
                return ResourceManager.GetString("Header_Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activités.
        /// </summary>
        public static string Header_Activities {
            get {
                return ResourceManager.GetString("Header_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer activité.
        /// </summary>
        public static string Header_AddActivity {
            get {
                return ResourceManager.GetString("Header_AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer groupe.
        /// </summary>
        public static string Header_AddGroup {
            get {
                return ResourceManager.GetString("Header_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter du personnel.
        /// </summary>
        public static string Header_AddPerson {
            get {
                return ResourceManager.GetString("Header_AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bénéficiaires.
        /// </summary>
        public static string Header_Beneficiary {
            get {
                return ResourceManager.GetString("Header_Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jours.
        /// </summary>
        public static string Header_Days {
            get {
                return ResourceManager.GetString("Header_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educateurs.
        /// </summary>
        public static string Header_Educators {
            get {
                return ResourceManager.GetString("Header_Educators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupes.
        /// </summary>
        public static string Header_Groups {
            get {
                return ResourceManager.GetString("Header_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les absences.
        /// </summary>
        public static string Header_ManageAbsence {
            get {
                return ResourceManager.GetString("Header_ManageAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les activités.
        /// </summary>
        public static string Header_ManageAtivity {
            get {
                return ResourceManager.GetString("Header_ManageAtivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les groupes.
        /// </summary>
        public static string Header_ManageGroup {
            get {
                return ResourceManager.GetString("Header_ManageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupations.
        /// </summary>
        public static string Header_WorkSummary {
            get {
                return ResourceManager.GetString("Header_WorkSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personne absente:.
        /// </summary>
        public static string Lbl_AbsentPerson {
            get {
                return ResourceManager.GetString("Lbl_AbsentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activité:.
        /// </summary>
        public static string Lbl_Activity {
            get {
                return ResourceManager.GetString("Lbl_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bénéficiaires:.
        /// </summary>
        public static string Lbl_Beneficiaries {
            get {
                return ResourceManager.GetString("Lbl_Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour:.
        /// </summary>
        public static string Lbl_Day {
            get {
                return ResourceManager.GetString("Lbl_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educateurs:.
        /// </summary>
        public static string Lbl_Educators {
            get {
                return ResourceManager.GetString("Lbl_Educators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        public static string Lbl_From {
            get {
                return ResourceManager.GetString("Lbl_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe:.
        /// </summary>
        public static string Lbl_Group {
            get {
                return ResourceManager.GetString("Lbl_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom:.
        /// </summary>
        public static string Lbl_Name {
            get {
                return ResourceManager.GetString("Lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moment:.
        /// </summary>
        public static string Lbl_Span {
            get {
                return ResourceManager.GetString("Lbl_Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom:.
        /// </summary>
        public static string Lbl_Surname {
            get {
                return ResourceManager.GetString("Lbl_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to au.
        /// </summary>
        public static string Lbl_To {
            get {
                return ResourceManager.GetString("Lbl_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au.
        /// </summary>
        public static string Lbl_ToU {
            get {
                return ResourceManager.GetString("Lbl_ToU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des horaires.
        /// </summary>
        public static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer cette absence?.
        /// </summary>
        public static string Msg_AskDeleteAbsence {
            get {
                return ResourceManager.GetString("Msg_AskDeleteAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer l&apos;activité &quot;{0}&quot;?.
        /// </summary>
        public static string Msg_AskDeleteActivity {
            get {
                return ResourceManager.GetString("Msg_AskDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer le groupe &quot;{0}&quot;?.
        /// </summary>
        public static string Msg_AskDeleteGroup {
            get {
                return ResourceManager.GetString("Msg_AskDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous effacer {0} {1}?.
        /// </summary>
        public static string Msg_AskDeletePerson {
            get {
                return ResourceManager.GetString("Msg_AskDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt..
        /// </summary>
        public static string Msg_NoMessage {
            get {
                return ResourceManager.GetString("Msg_NoMessage", resourceCulture);
            }
        }
    }
}
